---
- name: List Repositories from Nexus
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    nexus_username: admin
    nexus_password: admin123

  tasks:
  - name: List all repositories
    haxorof.sonatype_nexus.nexus_repository_info:
      url: "{{ nexus_url }}"
      validate_certs: false
      username: "{{ nexus_username }}"
      password: "{{ nexus_password }}"
    register: _result

  - name: Print _result
    ansible.builtin.debug:
      var: _result

  - name: List NuGet proxy repositories
    haxorof.sonatype_nexus.nexus_repository_info:
      url: "{{ nexus_url }}"
      validate_certs: false
      username: "{{ nexus_username }}"
      password: "{{ nexus_password }}"
      type: proxy
      format: nuget
    register: _result

  - name: Print _result
    ansible.builtin.debug:
      var: _result

  - name: List Maven proxy repositories
    haxorof.sonatype_nexus.nexus_repository_info:
      url: "{{ nexus_url }}"
      validate_certs: false
      username: "{{ nexus_username }}"
      password: "{{ nexus_password }}"
      type: proxy
      format: maven2
    register: _result

  - name: Print _result
    ansible.builtin.debug:
      var: _result

  - name: List maven-central
    haxorof.sonatype_nexus.nexus_repository_info:
      url: "{{ nexus_url }}"
      validate_certs: false
      username: "{{ nexus_username }}"
      password: "{{ nexus_password }}"
      name: maven-central
    register: _result

  - name: Print _result
    ansible.builtin.debug:
      var: _result
