---
- name: List Repositories from Nexus
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
  - name: List all repositories
    haxorof.sonatype_nexus.nexus_repository_info:
    register: _result

  - name: Print _result
    ansible.builtin.debug:
      var: _result

  - name: List NuGet proxy repositories
    haxorof.sonatype_nexus.nexus_repository_info:
      type: proxy
      format: nuget
    register: _result

  - name: Print _result
    ansible.builtin.debug:
      var: _result

  - name: List Maven proxy repositories
    haxorof.sonatype_nexus.nexus_repository_info:
      type: proxy
      format: maven2
    register: _result

  - name: Print _result
    ansible.builtin.debug:
      var: _result

  - name: List maven-central
    haxorof.sonatype_nexus.nexus_repository_info:
      name: maven-central
    register: _result

  - name: Print _result
    ansible.builtin.debug:
      var: _result
