---
- name: Manage P2 proxy Repositories in Nexus
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create P2 proxy repository
      haxorof.sonatype_nexus.nexus_repository_p2_proxy:
        state: present
        name: testproxy
        proxy:
          remote_url: https://download.eclipse.org/releases/2025-06
      loop:
        - change
        - no_change # Test idempotency

    - name: Delete P2 proxy repository
      haxorof.sonatype_nexus.nexus_repository_p2_proxy:
        state: absent
        name: testproxy
      loop:
        - change
        - no_change # Test idempotency
