---
- name: Manage Docker proxy repositories
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    nexus_username: admin
    nexus_password: admin123
    nexus_repos_docker_proxy:
      - name: docker-releases
        storage:
          blob_store_name: default
        proxy:
          remote_url: https://registry-1.docker.io

        docker_proxy:
          index_type: HUB

  tasks:
    - name: Create docker proxy repositories
      haxorof.sonatype_nexus.nexus_repository_docker_proxy:
        url: "{{ nexus_url }}"
        validate_certs: false
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        state: present
        name: "{{ item.name }}"
        storage: "{{ item.storage }}"
        proxy: "{{ item.proxy }}"
        docker_proxy: "{{ item.docker_proxy }}"
      loop: "{{ nexus_repos_docker_proxy }}"

    - name: Delete Docker proxy repositories
      haxorof.sonatype_nexus.nexus_repository_docker_proxy:
        url: "{{ nexus_url }}"
        validate_certs: false
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        name: "{{ item }}"
        state: absent
      loop: 
        - docker-releases
      tags:
        - molecule-idempotence-notest