---
- name: Manage Docker proxy repositories
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Create docker proxy repository
      haxorof.sonatype_nexus.nexus_repository_docker_proxy:
        state: present
        name: testproxy
        proxy:
          remote_url: https://registry-1.docker.io
        docker_proxy:
            index_type: HUB
      loop:
        - change
        - no_change # Test idempotency

    - name: Update docker proxy repository
      haxorof.sonatype_nexus.nexus_repository_docker_proxy:
        state: present
        name: testproxy
        proxy:
          remote_url: https://registry-1.docker.io/
        docker_proxy:
            index_type: HUB
      loop:
        - change
        - no_change # Test idempotency

    - name: Delete Docker proxy repository
      haxorof.sonatype_nexus.nexus_repository_docker_proxy:
        name: "{{ item }}"
        state: absent
      loop:
        - testproxy
        - testproxy # Test idempotency
      tags:
        - molecule-idempotence-notest
