---
- name: Manage Docker proxy repositories
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Create docker proxy repository
      haxorof.sonatype_nexus.nexus_repository_docker_proxy:
        url: "{{ nexus_url }}"
        validate_certs: false
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        state: present
        name: docker-hub
        storage:
          blob_store_name: default
        proxy:
          remote_url: https://registry-1.docker.io
        docker_proxy:
            index_type: HUB
      loop:
        - change
        - no_change # Test idempotency

    - name: Update docker proxy repository
      haxorof.sonatype_nexus.nexus_repository_docker_proxy:
        url: "{{ nexus_url }}"
        validate_certs: false
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        state: present
        name: docker-hub
        storage:
          blob_store_name: default
        proxy:
          remote_url: https://registry-1.docker.io/
        docker_proxy:
            index_type: HUB
      loop:
        - change
        - no_change # Test idempotency

    - name: Delete Docker proxy repository
      haxorof.sonatype_nexus.nexus_repository_docker_proxy:
        url: "{{ nexus_url }}"
        validate_certs: false
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        name: "{{ item }}"
        state: absent
      loop:
        - docker-hub
        - docker-hub # Test idempotency
      tags:
        - molecule-idempotence-notest
