---
- name: Manage blob stores of type file
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Create blob store of type file
      haxorof.sonatype_nexus.nexus_blobstore_file:
        name: testblob
        state: present
      register: _result
      tags:
        - molecule-idempotence-notest

    - name: Print _result
      ansible.builtin.debug:
        var: _result

    - name: Get blob store configuration
      haxorof.sonatype_nexus.nexus_blobstore_file_info:
        name: testblob
      register: _result

    - name: Print _result
      ansible.builtin.debug:
        var: _result

    - name: Delete blob store of type file
      haxorof.sonatype_nexus.nexus_blobstore_file:
        name: testblob
        state: absent
      register: _result
      tags:
        - molecule-idempotence-notest

    - name: Print _result
      ansible.builtin.debug:
        var: _result
