---
- name: Manage blob stores of type file
  hosts: localhost
  become: false
  gather_facts: no
  tasks:
  - name: Create blob store of type file
    haxorof.sonatype_nexus.nexus_blobstore_file:
      url: "{{ nexus_url }}"
      validate_certs: no
      name: default2
      username: admin
      password: admin123
      state: present
    register: _result
    tags:
      - molecule-idempotence-notest

  - name: Print _result
    ansible.builtin.debug:
      var: _result

  - name: Get blob store configuration
    haxorof.sonatype_nexus.nexus_blobstore_file_info:
      url: "{{ nexus_url }}"
      validate_certs: no
      name: default2
      username: admin
      password: admin123
    register: _result

  - name: Print _result
    ansible.builtin.debug:
      var: _result

  - name: Delete blob store of type file
    haxorof.sonatype_nexus.nexus_blobstore_file:
      url: "{{ nexus_url }}"
      validate_certs: no
      name: default2
      username: admin
      password: admin123
      state: absent
    register: _result
    tags:
      - molecule-idempotence-notest

  - name: Print _result
    ansible.builtin.debug:
      var: _result
