---
- name: Run Nexus scripts to configure features
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    nexus_script_name: "hello_world"

  tasks:
    - name: Upload Nexus script
      haxorof.sonatype_nexus.nexus_script:
        method: POST
        name: "{{ nexus_script_name }}"
        content: "println 'Hello, World!'"

    - name: Trigger script
      haxorof.sonatype_nexus.nexus_script_run:
        name: "{{ nexus_script_name }}"

    - name: Delete Nexus script
      haxorof.sonatype_nexus.nexus_script:
        method: DELETE
        name: "{{ nexus_script_name }}"
