---
- name: Manage anonymous setting
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    nexus_username: "admin"
    nexus_password: "admin123"

  tasks:
  - name: Get anonymous access setting
    haxorof.sonatype_nexus.nexus_security_anonymous_info:
      url: "{{ nexus_url }}"
      validate_certs: false
      username: "{{ nexus_username }}"
      password: "{{ nexus_password }}"
    register: _result

  - name: Print _result
    ansible.builtin.debug:
      var: _result

  - name: Set anonymous access setting (enable)
    haxorof.sonatype_nexus.nexus_security_anonymous:
      url: "{{ nexus_url }}"
      validate_certs: false
      username: "{{ nexus_username }}"
      password: "{{ nexus_password }}"
      user_id: anonymous
      realm_name: NexusAuthorizingRealm
      state: enabled
    tags:
      - molecule-idempotence-notest

  - name: Set anonymous access setting (disable)
    haxorof.sonatype_nexus.nexus_security_anonymous:
      url: "{{ nexus_url }}"
      validate_certs: false
      username: "{{ nexus_username }}"
      password: "{{ nexus_password }}"
      user_id: anonymous
      state: disabled
    tags:
      - molecule-idempotence-notest
