---
- name: Manage cleanup policies
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
  - name: Create/Update cleanup policy
    haxorof.sonatype_nexus.nexus_cleanup_policies:
      use_proxy: false
      validate_certs: false
      username: admin
      password: admin123
      name: test
      notes: This is a test cleanup policy
      format: "*"
      criteria_last_blob_updated: 30
      criteria_last_downloaded: 30
    register: _result
    delegate_to: 127.0.0.1

  - name: Print _result
    ansible.builtin.debug:
      var: _result

  - name: Delete cleanup policy
    haxorof.sonatype_nexus.nexus_cleanup_policies:
      use_proxy: false
      validate_certs: false
      username: admin
      password: admin123
      name: test
      state: absent
    register: _delete_result
    delegate_to: 127.0.0.1

  - name: Print _delete_result
    ansible.builtin.debug:
      var: _delete_result
