---
- name: Manage Nexus scripts on localhost
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    nexus_username: "admin"
    nexus_password: "admin123"
    nexus_script_name: "hello_world"

  tasks:
    - name: Upload Nexus script
      haxorof.sonatype_nexus.nexus_script:
        url: "{{ nexus_url }}"
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        validate_certs: false
        method: POST
        name: "{{ nexus_script_name }}"
        content: "println 'Hello, World!'"

    - name: Delete Nexus script
      haxorof.sonatype_nexus.nexus_script:
        url: "{{ nexus_url }}"
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        validate_certs: false
        method: DELETE
        name: "{{ nexus_script_name }}"
