---
- name: Manage raw hosted repository
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    nexus_username: admin
    nexus_password: admin123
    nexus_repos_raw_hosted:
      - name: raw-hosted
        storage:
          blob_store_name: default

  tasks:
    - name: Create hosted raw repository
      haxorof.sonatype_nexus.nexus_repository_raw_hosted:
        url: "{{ nexus_url }}"
        validate_certs: false
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        state: present
        name: "{{ item.name }}"
        storage: "{{ item.storage }}"
      with_items: "{{ nexus_repos_raw_hosted }}"
 
    - name: Delete hosted raw repository
      haxorof.sonatype_nexus.nexus_repository_raw_hosted:
        url: "{{ nexus_url }}"
        validate_certs: false
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        state: absent
        name: "{{ item.name }}"
      with_items: "{{ nexus_repos_raw_hosted }}"
