---
- name: User sources
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: List user sources
      haxorof.sonatype_nexus.nexus_security_user_sources_info:
      register: _result

    - name: Print _result
      ansible.builtin.debug:
        var: _result
