---
- name: Manage routing rules
  hosts: localhost
  become: false
  gather_facts: no
  tasks:
  - name: Create routing rule (block)
    haxorof.sonatype_nexus.nexus_routing_rule:
      url: "{{ nexus_url }}"
      validate_certs: no
      username: admin
      password: admin123
      name: blockrule
      description: This is a blocking routing rule
      mode: BLOCK
      matchers:
        - "^/com/example/.*"
        - "^/org/example/.*"
      state: present
    tags:
      - molecule-idempotence-notest

  - name: Create routing rule (allow)
    haxorof.sonatype_nexus.nexus_routing_rule:
      url: "{{ nexus_url }}"
      validate_certs: no
      username: admin
      password: admin123
      name: allowrule
      description: This is an allow routing rule
      mode: ALLOW
      matchers:
        - "^/com/myorg/.*"
      state: present
    tags:
      - molecule-idempotence-notest

  - name: List routing rules
    haxorof.sonatype_nexus.nexus_routing_rule_info:
      url: "{{ nexus_url }}"
      validate_certs: no
      username: admin
      password: admin123
    register: _result

  - name: Print _result
    ansible.builtin.debug:
      var: _result

  - name: Get routing rule blockrule
    haxorof.sonatype_nexus.nexus_routing_rule_info:
      url: "{{ nexus_url }}"
      validate_certs: no
      username: admin
      password: admin123
      name: blockrule
    register: _result

  - name: Print _result
    ansible.builtin.debug:
      var: _result

  - name: Delete routing rules
    haxorof.sonatype_nexus.nexus_routing_rule:
      url: "{{ nexus_url }}"
      validate_certs: no
      username: admin
      password: admin123
      name: "{{ item }}"
      state: absent
    with_items:
      - blockrule
      - allowrule
    tags:
      - molecule-idempotence-notest
