---
- name: Status checks
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
  - name: Readable check
    haxorof.sonatype_nexus.nexus_status_info:
      check_type: readable
    register: _result

  - name: Writable check
    haxorof.sonatype_nexus.nexus_status_info:
      check_type: writable
    register: _result

  - name: System status check
    haxorof.sonatype_nexus.nexus_status_info:
      check_type: system
    register: _result

  - name: Print _result
    ansible.builtin.debug:
      var: _result
