---
- name: Manage users
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    new_user_id: "testadmin"
    new_user_password: "testadmin"
    new_user_email: "testadmin@localhost"
    new_user_roles:
      - "nx-admin"

  tasks:
    - name: List users
      haxorof.sonatype_nexus.nexus_security_user_info:
      register: _result

    - name: Print _result
      ansible.builtin.debug:
        var: _result

    - name: List users from source 'default'
      haxorof.sonatype_nexus.nexus_security_user_info:
        source: default
      register: _result

    - name: Print _result
      ansible.builtin.debug:
        var: _result

    - name: Create user
      haxorof.sonatype_nexus.nexus_security_user:
        user_id: "{{ new_user_id }}"
        user_password: "{{ new_user_password }}"
        first_name: My
        last_name: Admin
        email_address: "{{ new_user_email }}"
        status: active
        roles: "{{ new_user_roles }}"
        state: present
      tags:
        - molecule-idempotence-notest

    - name: Get created user info
      haxorof.sonatype_nexus.nexus_security_user_info:
        user_id: "{{ new_user_id }}"
      register: _result

    - name: Print _result
      ansible.builtin.debug:
        var: _result

    - name: Disable user
      haxorof.sonatype_nexus.nexus_security_user:
        user_id: "{{ new_user_id }}"
        status: disabled
        state: present
      tags:
        - molecule-idempotence-notest

    - name: Delete user
      haxorof.sonatype_nexus.nexus_security_user:
        user_id: "{{ new_user_id }}"
        state: absent
      tags:
        - molecule-idempotence-notest
