---
- name: Manage read-only
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
  - name: Enable read-only
    haxorof.sonatype_nexus.nexus_read_only:
      status: freeze
    tags:
      - molecule-idempotence-notest

  - name: Get read-only system status
    haxorof.sonatype_nexus.nexus_read_only_info:

  - name: Release read-only
    haxorof.sonatype_nexus.nexus_read_only:
      status: release
    tags:
      - molecule-idempotence-notest

  - name: Forcibly release read-only
    haxorof.sonatype_nexus.nexus_read_only:
      status: force-release
    tags:
      - molecule-idempotence-notest
