---
- name: Manage read-only
  hosts: localhost
  become: false
  gather_facts: no
  tasks:
  - name: Enable read-only
    haxorof.sonatype_nexus.nexus_read_only:
      url: http://{{ nexus_host }}:8081
      validate_certs: no
      username: admin
      password: "{{ lookup('env', 'NEXUS_PASSWORD') | default('password') }}"
      status: freeze

  - name: Get read-only system status
    haxorof.sonatype_nexus.nexus_read_only_info:
      url: http://{{ nexus_host }}:8081
      validate_certs: no
      username: admin
      password: admin123

  - name: Release read-only
    haxorof.sonatype_nexus.nexus_read_only:
      url: http://{{ nexus_host }}:8081
      validate_certs: no
      username: admin
      password: admin123
      status: release

  - name: Forcibly release read-only
    haxorof.sonatype_nexus.nexus_read_only:
      url: http://{{ nexus_host }}:8081
      validate_certs: no
      username: admin
      password: admin123
      status: force-release
