---
- name: Manage read-only
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    nexus_username: "admin"
    nexus_password: "admin123"

  tasks:
  - name: Enable read-only
    haxorof.sonatype_nexus.nexus_read_only:
      url: "{{ nexus_url }}"
      validate_certs: false
      username: "{{ nexus_username }}"
      password: "{{ nexus_password }}"
      status: freeze
    tags:
      - molecule-idempotence-notest

  - name: Get read-only system status
    haxorof.sonatype_nexus.nexus_read_only_info:
      url: "{{ nexus_url }}"
      validate_certs: false
      username: "{{ nexus_username }}"
      password: "{{ nexus_password }}"

  - name: Release read-only
    haxorof.sonatype_nexus.nexus_read_only:
      url: "{{ nexus_url }}"
      validate_certs: false
      username: "{{ nexus_username }}"
      password: "{{ nexus_password }}"
      status: release
    tags:
      - molecule-idempotence-notest

  - name: Forcibly release read-only
    haxorof.sonatype_nexus.nexus_read_only:
      url: "{{ nexus_url }}"
      validate_certs: false
      username: "{{ nexus_username }}"
      password: "{{ nexus_password }}"
      status: force-release
    tags:
      - molecule-idempotence-notest
