---
- name: Manage LDAP servers and set order safely
  hosts: localhost
  gather_facts: false

  vars:
    nexus_admin_user: "admin"
    nexus_admin_password: "admin123"

  pre_tasks:
    - name: Ensure LDAP server 'primary' exists
      haxorof.sonatype_nexus.nexus_security_ldap:
        url: "{{ nexus_url }}"
        username: "{{ nexus_admin_user }}"
        password: "{{ nexus_admin_password }}"
        validate_certs: false
        state: present
        ldap_name: "primary"
        ldap_protocol: "ldap"
        ldap_use_trust_store: false
        ldap_host: "ldap.example.com"
        ldap_port: 389
        ldap_search_base: "dc=example,dc=com"
        ldap_auth_scheme: "SIMPLE"
        ldap_auth_username: "trypass"
        ldap_auth_password: "secretpassword"
        ldap_connection_timeout_seconds: 30
        ldap_connection_retry_delay_seconds: 300
        ldap_max_incidents_count: 3
        ldap_user_subtree: true
        ldap_user_object_class: "user"
        ldap_user_id_attribute: "sAMAccountName"
        ldap_user_real_name_attribute: "cn"
        ldap_user_email_address_attribute: "mail"

    - name: Ensure LDAP server 'secondary' exists
      haxorof.sonatype_nexus.nexus_security_ldap:
        url: "{{ nexus_url }}"
        username: "{{ nexus_admin_user }}"
        password: "{{ nexus_admin_password }}"
        validate_certs: false
        state: present
        ldap_name: "secondary"
        ldap_protocol: "ldap"
        ldap_use_trust_store: false
        ldap_host: "ldap.example.com"
        ldap_port: 633
        ldap_search_base: "dc=example,dc=com"
        ldap_auth_scheme: "SIMPLE"
        ldap_auth_username: "trypass"
        ldap_auth_password: "secretpassword"
        ldap_connection_timeout_seconds: 30
        ldap_connection_retry_delay_seconds: 300
        ldap_max_incidents_count: 3
        ldap_user_subtree: true
        ldap_user_object_class: "user"
        ldap_user_id_attribute: "sAMAccountName"
        ldap_user_real_name_attribute: "cn"
        ldap_user_email_address_attribute: "mail"

  tasks:
    - name: Set LDAP server order (only if supported)
      haxorof.sonatype_nexus.nexus_security_ldap_order:
        url: "{{ nexus_url }}"
        username: "{{ nexus_admin_user }}"
        password: "{{ nexus_admin_password }}"
        validate_certs: false
        order_list:
          - primary
          - secondary

  post_tasks:
    - name: Remove LDAP server 'primary'
      haxorof.sonatype_nexus.nexus_security_ldap:
        url: "{{ nexus_url }}"
        username: "{{ nexus_admin_user }}"
        password: "{{ nexus_admin_password }}"
        validate_certs: false
        state: absent
        ldap_name: "primary"

    - name: Remove LDAP server 'secondary'
      haxorof.sonatype_nexus.nexus_security_ldap:
        url: "{{ nexus_url }}"
        username: "{{ nexus_admin_user }}"
        password: "{{ nexus_admin_password }}"
        validate_certs: false
        state: absent
        ldap_name: "secondary"
