---
- name: Manage Nexus LDAP Configuration Without Common Vars
  hosts: localhost
  gather_facts: false

  vars:
    nexus_admin_user: "admin"
    nexus_admin_password: "admin123"

  tasks:
    - name: Get existing LDAP server
      haxorof.sonatype_nexus.nexus_security_ldap:
        url: "{{ nexus_url }}"
        username: "{{ nexus_admin_user }}"
        password: "{{ nexus_admin_password }}"
        method: GET
        ldap_name: "primary"
      register: ldap_server_list

    - name: Debug LDAP server info
      debug:
        var: ldap_server_list

    - name: Create LDAP server primary
      haxorof.sonatype_nexus.nexus_security_ldap:
        url: "{{ nexus_url }}"
        username: "{{ nexus_admin_user }}"
        password: "{{ nexus_admin_password }}"
        validate_certs: false
        state: present
        ldap_name: "primary"
        ldap_protocol: "ldap"
        ldap_use_trust_store: false
        ldap_host: "ldap.example.com"
        ldap_port: 3635
        ldap_search_base: "dc=example,dc=com"
        ldap_auth_scheme: "SIMPLE"
        ldap_auth_username: "trypass"
        ldap_auth_password: "secretpassword"
        ldap_connection_timeout_seconds: 30
        ldap_connection_retry_delay_seconds: 300
        ldap_max_incidents_count: 3
        ldap_user_subtree: true
        ldap_user_object_class: "user"
        ldap_user_id_attribute: "sAMAccountName"
        ldap_user_real_name_attribute: "cn"
        ldap_user_email_address_attribute: "mail"

    - name: UPDATE LDAP server name only (OBS! only run ones)
      haxorof.sonatype_nexus.nexus_security_ldap:
        url: "{{ nexus_url }}"
        username: "{{ nexus_admin_user }}"
        password: "{{ nexus_admin_password }}"
        validate_certs: false
        state: present
        current_ldap_name: "primary" # Current ldap name
        ldap_name: "secondary" # New ldap name
        ldap_protocol: "ldap"
        ldap_use_trust_store: false
        ldap_host: "ldap.example.com"
        ldap_port: 6333
        ldap_search_base: "dc=example,dc=com"
        ldap_auth_scheme: "SIMPLE"
        ldap_auth_username: "trypass"
        ldap_auth_password: "secretpassword"
        ldap_connection_timeout_seconds: 30
        ldap_connection_retry_delay_seconds: 300
        ldap_max_incidents_count: 3
        ldap_user_subtree: true
        ldap_user_object_class: "user"
        ldap_user_id_attribute: "sAMAccountName"
        ldap_user_real_name_attribute: "cn"
        ldap_user_email_address_attribute: "mail"
      register: ldap_server_update_name

    - name: Debug updated LDAP server name
      debug:
        var: ldap_server_update_name

    - name: UPDATE LDAP server secondary (update LDAP config)
      haxorof.sonatype_nexus.nexus_security_ldap:
        url: "{{ nexus_url }}"
        username: "{{ nexus_admin_user }}"
        password: "{{ nexus_admin_password }}"
        validate_certs: false
        state: present
        ldap_name: "secondary"
        ldap_protocol: "ldap"
        ldap_use_trust_store: false
        ldap_host: "ldap.example.com"
        ldap_port: 633
        ldap_search_base: "dc=example,dc=com"
        ldap_auth_scheme: "SIMPLE"
        ldap_auth_username: "trypass"
        ldap_auth_password: "secretpassword"
        ldap_connection_timeout_seconds: 30
        ldap_connection_retry_delay_seconds: 300
        ldap_max_incidents_count: 3
        ldap_user_subtree: true
        ldap_user_object_class: "user"
        ldap_user_id_attribute: "sAMAccountName"
        ldap_user_real_name_attribute: "cn"
        ldap_user_email_address_attribute: "mail"
      register: ldap_server_update

    - name: Debug updated LDAP config
      debug:
        var: ldap_server_update

    - name: Remove secondary LDAP server if it exists
      haxorof.sonatype_nexus.nexus_security_ldap:
        url: "{{ nexus_url }}"
        username: "{{ nexus_admin_user }}"
        password: "{{ nexus_admin_password }}"
        ldap_name: secondary
        state: absent
