---
- name: Manage Nexus Go proxy repository in nexus
  hosts: localhost
  gather_facts: false

  vars:
    nexus_username: admin
    nexus_password: admin123
    blob_store_name: default
    nexus_repos_go_proxy:
      - name: go-proxy
        storage:
          blob_store_name: "{{ blob_store_name }}"
        proxy:
          remote_url: https://example.com/go

  tasks:
    - name: Create Go proxy repositories
      haxorof.sonatype_nexus.nexus_repository_go_proxy:
        url: "{{ nexus_url }}"
        validate_certs: false
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        state: present
        name: "{{ item.name }}"
        storage: "{{ item.storage }}"
        proxy: "{{ item.proxy }}"
      loop: "{{ nexus_repos_go_proxy }}"

    - name: Delete a Go proxy repository
      haxorof.sonatype_nexus.nexus_repository_go_proxy:
        url: "{{ nexus_url }}"
        validate_certs: false
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        state: absent
        name: go-proxy