---
- name: Manage Maven proxy repositories
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Create Maven proxy repositories
      haxorof.sonatype_nexus.nexus_repository_maven_proxy:
        state: present
        name: testproxy
        proxy:
          remote_url: https://repo1.maven.org/maven2/
      loop:
        - change
        - no_change # Test idempotency

    - name: Delete Maven proxy repositories
      haxorof.sonatype_nexus.nexus_repository_maven_proxy:
        name: testproxy
        state: absent
      loop:
        - change
        - no_change # Test idempotency

