---
- name: Manage Maven proxy repositories
  hosts: localhost
  become: false
  gather_facts: no
  tasks:
  - name: Create Maven proxy repository
    haxorof.sonatype_nexus.nexus_repository_maven_proxy:
      url: http://{{ nexus_host }}:8081
      validate_certs: no
      username: admin
      password: admin123
      state: present
      name: testrepo
  #     online: yes
      storage:
        blob_store_name: default
  #       strict_content_type_validation: yes
  #     cleanup:
  #       policy_names: [
  #         "string"
  #       ]
      proxy:
        remote_url: http://localhost:8081/repository/maven-public/
  #       content_max_age: 1440
  #       meta_data_max_age: 1440
  #     negative_cache:
  #       enabled: yes
  #       time_to_live: 1440
  #     http_client:
  #       blocked: no
  #       auto_block: yes
  #       connection:
  #         retries: 0
  #         user_agent_suffix: string
  #         timeout: 60
  #         enable_circular_redirects: no
  #         enable_cookies: no
  #         use_trust_store: no
  #       authentication:
  #         type: username
  #         username: string
  #         password: string
  #         ntlmHost: string
  #         ntlmDomain: string
  #         preemptive: no
  #     routing_rule: string
  #     replication:
  #       preemptive_pull_enabled: no
  #       asset_path_regex: string
  #     maven:
  #       version_policy: MIXED
  #       layout_policy: STRICT
  #       content_disposition: ATTACHMENT

  - name: Delete Maven proxy repository
    haxorof.sonatype_nexus.nexus_repository_maven_proxy:
      url: http://{{ nexus_host }}:8081
      validate_certs: no
      username: admin
      password: admin123
      name: testrepo
      state: absent
