---
- name: Manage Maven proxy repositories
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    nexus_repos_maven_proxy:
      - name: maven-internal-releases
        storage:
          blob_store_name: default
        proxy:
          remote_url: https://repo1.maven.org/maven2/

  tasks:
    - name: Create Maven proxy repositories
      haxorof.sonatype_nexus.nexus_repository_maven_proxy:
        url: "{{ nexus_url }}"
        validate_certs: false
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        state: present
        name: "{{ item.name }}"
        storage: "{{ item.storage }}"
        proxy: "{{ item.proxy }}"
      loop: "{{ nexus_repos_maven_proxy }}"
      register: maven_proxy_value

    - name: Debug Maven proxy repositories result
      debug:
        var: maven_proxy_value

    - name: Delete Maven proxy repositories
      haxorof.sonatype_nexus.nexus_repository_maven_proxy:
        url: "{{ nexus_url }}"
        validate_certs: false
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        name: "{{ item }}"
        state: absent
      loop:
        - maven-internal-releases
      tags:
        - molecule-idempotence-notest

