name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: ansible-galaxy version
        run: ansible-galaxy --version

      - name: Test to build Ansible collection
        run: ansible-galaxy collection build --force --ignore-certs

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Ensure all shell script having the executable flag
        run: chmod +x *.sh
        working-directory: ./samples

      - name: Setup Ansible for testing
        run: ./setup_ansible.sh
        working-directory: ./samples

      - name: Setup Nexus 3
        run: ./setup_nexus.sh
        working-directory: ./samples
        env:
          NEXUS_HOST: localhost

      - name: Run samples
        run: ./run_samples.sh
        working-directory: ./samples
        env:
          NEXUS_HOST: localhost

      - name: Teardown Nexus 3
        run: ./teardown_nexus.sh
        working-directory: ./samples
        env:
          NEXUS_HOST: localhost