---
- name: Retrieve Nexus Roles Information
  hosts: localhost
  become: false
  gather_facts: false

  vars:
    nexus_username: "admin"
    nexus_password: "admin123"

  tasks:
    - name: Get specific Nexus role
      haxorof.sonatype_nexus.nexus_roles_info:
        url: "{{ nexus_url }}"
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        name: view-anonymous
        validate_certs: false
        use_proxy: false
      register: role_info

    - name: Debug roles info
      debug:
        var: role_info

    - name: List all Nexus roles
      haxorof.sonatype_nexus.nexus_roles_info:
        url: "{{ nexus_url }}"
        username: "{{ nexus_username }}"
        password: "{{ nexus_password }}"
        validate_certs: false
        use_proxy: false
      register: roles_list

    - name: Debug all roles
      debug:
        var: roles_list